2025-07-21 23:29:45,381 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-21 23:34:42,971 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-21 23:37:53,722 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-21 23:38:46,632 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-10' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=BadRequest("Can't parse inline keyboard button: inlinekeyboardbutton must be an object")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 104, in start_handler
    await message.answer(text, reply_markup=markup)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/types/message.py", line 438, in answer
    return await self.bot.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Can't parse inline keyboard button: inlinekeyboardbutton must be an object
2025-07-21 23:40:39,991 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=BadRequest("Can't parse inline keyboard button: inlinekeyboardbutton must be an object")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 104, in start_handler
    await message.answer(text, reply_markup=markup)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/types/message.py", line 438, in answer
    return await self.bot.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Can't parse inline keyboard button: inlinekeyboardbutton must be an object
2025-07-21 23:40:59,261 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-21 23:43:26,391 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-12' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=BadRequest("Can't parse inline keyboard button: inlinekeyboardbutton must be an object")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 104, in start_handler
    await message.answer(text, reply_markup=markup)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/types/message.py", line 438, in answer
    return await self.bot.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Can't parse inline keyboard button: inlinekeyboardbutton must be an object
2025-07-21 23:45:21,781 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-21 23:48:57,892 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-21 23:52:13,004 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-21 23:55:42,546 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 00:03:01,589 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 00:05:11,522 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 00:10:45,988 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 00:11:24,271 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 00:27:40,028 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 00:29:25,429 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 00:30:30,632 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 01:37:33,998 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 01:40:20,551 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 01:47:44,549 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 01:48:09,237 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=ChatNotFound('Chat not found')>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 9, in wrapper
    if not await check_subs(message.from_user.id):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/utils.py", line 8, in check_subs
    member = await Bot.get_current().get_chat_member(chat_id=ch, user_id=user_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2682, in get_chat_member
    result = await self.request(api.Methods.GET_CHAT_MEMBER, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-22 01:48:36,373 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-64' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=ChatNotFound('Chat not found')>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 9, in wrapper
    if not await check_subs(message.from_user.id):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/utils.py", line 8, in check_subs
    member = await Bot.get_current().get_chat_member(chat_id=ch, user_id=user_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2682, in get_chat_member
    result = await self.request(api.Methods.GET_CHAT_MEMBER, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-22 01:48:37,500 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-69' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=ChatNotFound('Chat not found')>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 9, in wrapper
    if not await check_subs(message.from_user.id):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/utils.py", line 8, in check_subs
    member = await Bot.get_current().get_chat_member(chat_id=ch, user_id=user_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2682, in get_chat_member
    result = await self.request(api.Methods.GET_CHAT_MEMBER, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-22 01:56:14,616 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 01:56:22,195 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-12' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=ChatNotFound('Chat not found')>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 9, in wrapper
    if not await check_subs(message.from_user.id):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/utils.py", line 8, in check_subs
    member = await Bot.get_current().get_chat_member(chat_id=ch, user_id=user_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2682, in get_chat_member
    result = await self.request(api.Methods.GET_CHAT_MEMBER, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-22 01:56:22,911 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-17' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=ChatNotFound('Chat not found')>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 9, in wrapper
    if not await check_subs(message.from_user.id):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/utils.py", line 8, in check_subs
    member = await Bot.get_current().get_chat_member(chat_id=ch, user_id=user_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2682, in get_chat_member
    result = await self.request(api.Methods.GET_CHAT_MEMBER, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-22 01:56:23,123 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-22' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=ChatNotFound('Chat not found')>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 9, in wrapper
    if not await check_subs(message.from_user.id):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/utils.py", line 8, in check_subs
    member = await Bot.get_current().get_chat_member(chat_id=ch, user_id=user_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2682, in get_chat_member
    result = await self.request(api.Methods.GET_CHAT_MEMBER, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-22 01:56:23,339 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-26' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=ChatNotFound('Chat not found')>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 9, in wrapper
    if not await check_subs(message.from_user.id):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/utils.py", line 8, in check_subs
    member = await Bot.get_current().get_chat_member(chat_id=ch, user_id=user_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2682, in get_chat_member
    result = await self.request(api.Methods.GET_CHAT_MEMBER, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-22 01:56:23,551 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-30' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=ChatNotFound('Chat not found')>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 9, in wrapper
    if not await check_subs(message.from_user.id):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/utils.py", line 8, in check_subs
    member = await Bot.get_current().get_chat_member(chat_id=ch, user_id=user_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2682, in get_chat_member
    result = await self.request(api.Methods.GET_CHAT_MEMBER, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-22 01:56:23,986 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-34' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=ChatNotFound('Chat not found')>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 9, in wrapper
    if not await check_subs(message.from_user.id):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/utils.py", line 8, in check_subs
    member = await Bot.get_current().get_chat_member(chat_id=ch, user_id=user_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2682, in get_chat_member
    result = await self.request(api.Methods.GET_CHAT_MEMBER, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-22 02:01:09,116 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 02:09:23,433 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 02:15:22,201 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 02:15:29,220 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-6' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=TypeError("object function can't be used in 'await' expression")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object function can't be used in 'await' expression
2025-07-22 02:15:39,251 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-12' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=TypeError("object function can't be used in 'await' expression")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object function can't be used in 'await' expression
2025-07-22 02:15:40,349 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-20' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=TypeError("object function can't be used in 'await' expression")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object function can't be used in 'await' expression
2025-07-22 02:15:41,171 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-24' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=TypeError("object function can't be used in 'await' expression")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object function can't be used in 'await' expression
2025-07-22 02:15:41,885 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-28' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=TypeError("object function can't be used in 'await' expression")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object function can't be used in 'await' expression
2025-07-22 02:15:42,192 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-32' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=TypeError("object function can't be used in 'await' expression")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object function can't be used in 'await' expression
2025-07-22 02:15:42,405 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-35' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=TypeError("object function can't be used in 'await' expression")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object function can't be used in 'await' expression
2025-07-22 02:15:42,704 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-38' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=TypeError("object function can't be used in 'await' expression")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object function can't be used in 'await' expression
2025-07-22 02:15:42,918 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-42' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=TypeError("object function can't be used in 'await' expression")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object function can't be used in 'await' expression
2025-07-22 02:16:55,306 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 02:16:59,653 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-6' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=TypeError("object function can't be used in 'await' expression")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object function can't be used in 'await' expression
2025-07-22 02:18:53,469 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 02:20:15,911 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-132' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=TypeError("get_not_subscribed_channels() missing 1 required positional argument: 'user_id'")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 188, in recheck_subs
    not_joined = await get_not_subscribed_channels(user_id)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_not_subscribed_channels() missing 1 required positional argument: 'user_id'
2025-07-22 02:21:51,149 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 23:33:57,581 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 23:34:36,997 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-46' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=AttributeError("'dict' object has no attribute 'username'")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 15, in wrapper
    text += f"🔸 <a href='https://t.me/{ch.username}'>{ch.title}</a>\n"
                                        ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'username'
2025-07-22 23:34:38,113 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-53' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=AttributeError("'dict' object has no attribute 'username'")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 15, in wrapper
    text += f"🔸 <a href='https://t.me/{ch.username}'>{ch.title}</a>\n"
                                        ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'username'
2025-07-22 23:34:39,038 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-60' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=AttributeError("'dict' object has no attribute 'username'")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 15, in wrapper
    text += f"🔸 <a href='https://t.me/{ch.username}'>{ch.title}</a>\n"
                                        ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'username'
2025-07-22 23:39:00,917 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 23:46:44,323 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 23:47:14,230 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-25' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=TypeError("'>=' not supported between instances of 'list' and 'int'")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 28, in wrapper
    return await handler(message, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 77, in secret_group_access
    if referrals >= 20 and bonus_level < 1:
       ^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'list' and 'int'
2025-07-22 23:49:59,781 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-22 23:50:14,668 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=TypeError("'>=' not supported between instances of 'list' and 'int'")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 28, in wrapper
    return await handler(message, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 81, in secret_group_access
    elif referrals >= 40 and bonus_level < 2:
         ^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'list' and 'int'
2025-07-22 23:50:21,601 - aiogram.dispatcher.dispatcher - WARNING - Polling is stopped.
2025-07-22 23:50:21,605 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-19' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=TypeError("'>=' not supported between instances of 'list' and 'int'")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 28, in wrapper
    return await handler(message, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 81, in secret_group_access
    elif referrals >= 40 and bonus_level < 2:
         ^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'list' and 'int'
2025-07-22 23:50:21,672 - aiogram.dispatcher.dispatcher - INFO - Stop polling...
2025-07-22 23:51:25,340 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 20:22:30,362 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 20:27:16,870 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 20:30:40,658 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 20:36:36,952 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 20:42:45,669 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 20:43:53,856 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-55' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=ChatNotFound('Chat not found')>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 36, in wrapper
    return await handler(message, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 78, in secret_group_access
    await send_secret_channel(message, 1)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 63, in send_secret_channel
    await bot.send_message(
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-23 20:44:05,986 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-65' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=ChatNotFound('Chat not found')>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 36, in wrapper
    return await handler(message, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 78, in secret_group_access
    await send_secret_channel(message, 1)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 63, in send_secret_channel
    await bot.send_message(
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-23 20:44:31,561 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 20:44:42,414 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-6' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=ChatNotFound('Chat not found')>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 36, in wrapper
    return await handler(message, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 78, in secret_group_access
    await send_secret_channel(message, 1)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 63, in send_secret_channel
    await bot.send_message(
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-23 20:46:05,186 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-19' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=ChatNotFound('Chat not found')>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 36, in wrapper
    return await handler(message, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 78, in secret_group_access
    await send_secret_channel(message, 1)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 63, in send_secret_channel
    await bot.send_message(
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-23 21:48:29,308 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 21:51:01,985 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 21:55:32,960 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 21:55:40,295 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-6' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=KeyError('title')>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 177, in recheck_subs
    text += f"🔸 <a href='https://t.me/{ch['username'][1:]}'>{ch['title']}</a>\n"
                                                              ~~^^^^^^^^^
KeyError: 'title'
2025-07-23 21:57:13,470 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 21:57:23,838 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-6' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=KeyError('title')>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 116, in start_handler
    text += f"🔸 <a href='https://t.me/{ch['username'][1:]}'>{ch['title']}</a>\n"
                                                              ~~^^^^^^^^^
KeyError: 'title'
2025-07-23 21:59:36,064 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 22:00:42,175 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-44' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=TypeError("unhashable type: 'slice'")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 116, in start_handler
    text += f"🔸 <a href='https://t.me/{ch['username'][1:]}'>{ch['title']}</a>\n"
                                        ~~~~~~~~~~~~~~^^^^
TypeError: unhashable type: 'slice'
2025-07-23 22:00:45,636 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-55' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=AttributeError("'dict' object has no attribute 'lstrip'")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 17, in wrapper
    username = ch.get("username", "").lstrip("@")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lstrip'
2025-07-23 22:00:46,987 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-63' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=AttributeError("'dict' object has no attribute 'lstrip'")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 17, in wrapper
    username = ch.get("username", "").lstrip("@")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lstrip'
2025-07-23 22:00:48,523 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-71' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=AttributeError("'dict' object has no attribute 'lstrip'")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 17, in wrapper
    username = ch.get("username", "").lstrip("@")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lstrip'
2025-07-23 22:02:46,426 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 22:02:52,940 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-10' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=AttributeError("'dict' object has no attribute 'lstrip'")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 17, in wrapper
    username = ch.get("username", "").lstrip("@")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lstrip'
2025-07-23 22:02:53,863 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-19' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=AttributeError("'dict' object has no attribute 'lstrip'")>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 17, in wrapper
    username = ch.get("username", "").lstrip("@")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lstrip'
2025-07-23 22:03:15,564 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 22:05:08,492 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 22:10:03,905 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 22:16:48,881 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 22:21:00,979 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 22:22:00,536 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 22:26:56,590 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 22:29:59,784 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 22:31:49,746 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 22:44:46,713 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-23 22:45:25,550 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 15:23:43,143 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 15:24:04,120 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 15:25:49,160 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 15:26:25,275 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 15:49:04,530 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 15:50:48,816 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 16:04:34,828 - aiogram.dispatcher.dispatcher - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 382, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-07-24 16:04:45,383 - aiogram.dispatcher.dispatcher - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 382, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-07-24 16:04:56,020 - aiogram.dispatcher.dispatcher - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 382, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-07-24 21:55:58,264 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 21:56:05,671 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 22:00:02,957 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 22:02:34,524 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 22:03:16,994 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 22:07:28,028 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 22:14:26,330 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 22:16:43,606 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 22:18:51,537 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 22:21:36,035 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 22:22:57,196 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 22:25:08,747 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 22:26:32,966 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 22:50:29,804 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 22:52:17,133 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 22:54:11,706 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 22:54:40,503 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 22:56:48,508 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:03:02,972 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:03:28,956 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:03:32,903 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-6' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=BadRequest('Message caption is too long')>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 41, in wrapper
    return await handler(message, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 335, in send_referral_link
    await message.answer_photo(
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/types/message.py", line 511, in answer_photo
    return await self.bot.send_photo(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 565, in send_photo
    result = await self.request(api.Methods.SEND_PHOTO, payload, files)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Message caption is too long
2025-07-24 23:03:39,045 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-26' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=BadRequest('Message caption is too long')>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 41, in wrapper
    return await handler(message, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 335, in send_referral_link
    await message.answer_photo(
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/types/message.py", line 511, in answer_photo
    return await self.bot.send_photo(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 565, in send_photo
    result = await self.request(api.Methods.SEND_PHOTO, payload, files)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 141, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Message caption is too long
2025-07-24 23:05:57,650 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:06:48,251 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:13:24,833 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:14:08,113 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:14:54,835 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:14:57,172 - aiogram.dispatcher.dispatcher - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 382, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-07-24 23:15:02,576 - aiogram.dispatcher.dispatcher - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 382, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-07-24 23:15:07,903 - aiogram.dispatcher.dispatcher - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 382, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-07-24 23:15:11,931 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:15:13,323 - aiogram.dispatcher.dispatcher - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 382, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-07-24 23:15:18,651 - aiogram.dispatcher.dispatcher - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 382, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-07-24 23:15:23,977 - aiogram.dispatcher.dispatcher - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 382, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-07-24 23:15:29,300 - aiogram.dispatcher.dispatcher - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 382, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-07-24 23:15:31,403 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:15:34,626 - aiogram.dispatcher.dispatcher - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 382, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-07-24 23:15:39,958 - aiogram.dispatcher.dispatcher - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 382, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-07-24 23:15:45,290 - aiogram.dispatcher.dispatcher - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 382, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-07-24 23:15:50,614 - aiogram.dispatcher.dispatcher - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 382, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-07-24 23:15:55,935 - aiogram.dispatcher.dispatcher - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 382, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-07-24 23:16:01,261 - aiogram.dispatcher.dispatcher - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 382, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-07-24 23:16:06,585 - aiogram.dispatcher.dispatcher - ERROR - Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 382, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2025-07-24 23:16:13,840 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:17:45,066 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:19:42,133 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:21:53,000 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:23:01,528 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:24:18,888 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:25:19,518 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:30:27,993 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:31:01,761 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Dispatcher._process_polling_updates() done, defined at /home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py:410> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 418, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 236, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 257, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/decorators.py", line 41, in wrapper
    return await handler(message, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 78, in secret_group_access
    photo = types.InputFile("media/bonus.jpg")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/types/input_file.py", line 40, in __init__
    self._file = open(path_or_bytesio, 'rb')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'media/bonus.jpg'
2025-07-24 23:31:37,028 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:45:49,086 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:45:55,024 - root - ERROR - Havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 63, in send_secret_channel
    invite_link: ChatInviteLink = await bot.create_chat_invite_link(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2210, in create_chat_invite_link
    result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-24 23:46:07,379 - aiogram.dispatcher.dispatcher - WARNING - Polling is stopped.
2025-07-24 23:46:07,418 - aiogram.dispatcher.dispatcher - INFO - Stop polling...
2025-07-24 23:47:39,020 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:48:53,276 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:49:04,650 - root - ERROR - Havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 63, in send_secret_channel
    invite_link: ChatInviteLink = await bot.create_chat_invite_link(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2210, in create_chat_invite_link
    result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-24 23:50:25,251 - aiogram.dispatcher.dispatcher - WARNING - Polling is stopped.
2025-07-24 23:50:25,289 - aiogram.dispatcher.dispatcher - INFO - Stop polling...
2025-07-24 23:50:44,744 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:51:13,440 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:51:17,565 - root - ERROR - Havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 63, in send_secret_channel
    invite_link: ChatInviteLink = await bot.create_chat_invite_link(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2210, in create_chat_invite_link
    result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-24 23:55:48,931 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:56:06,087 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-24 23:56:09,419 - root - ERROR - ❌ Havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 65, in send_secret_channel
    invite_link: ChatInviteLink = await bot.create_chat_invite_link(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2210, in create_chat_invite_link
    result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-25 00:06:11,014 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-25 00:06:31,237 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-25 00:06:34,257 - root - ERROR - ❌ Havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 71, in send_secret_channel
    expire_date=datetime.now() + timedelta(days=1),
                ^^^^^^^^
NameError: name 'datetime' is not defined
2025-07-25 00:07:51,516 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-25 00:08:03,371 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-25 00:08:06,418 - root - ERROR - ❌ Havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 72, in send_secret_channel
    invite_link: ChatInviteLink = await bot.create_chat_invite_link(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2210, in create_chat_invite_link
    result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-25 00:09:15,953 - root - ERROR - ❌ Havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 72, in send_secret_channel
    invite_link: ChatInviteLink = await bot.create_chat_invite_link(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2210, in create_chat_invite_link
    result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-25 00:12:45,185 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-25 00:18:09,823 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-25 00:18:26,118 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-25 00:18:29,539 - root - ERROR - ❌ Maxsus havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 80, in send_secret_channel
    invite_link: ChatInviteLink = await bot.create_chat_invite_link(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2210, in create_chat_invite_link
    result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-25 00:19:30,680 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-25 00:19:34,347 - root - ERROR - ❌ 1-bosqich havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 80, in send_secret_channel
    invite_link: ChatInviteLink = await bot.create_chat_invite_link(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2210, in create_chat_invite_link
    result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-25 00:19:34,653 - root - ERROR - ❌ 2-bosqich havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 80, in send_secret_channel
    invite_link: ChatInviteLink = await bot.create_chat_invite_link(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2210, in create_chat_invite_link
    result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-25 00:19:34,900 - root - ERROR - ❌ 3-bosqich havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 80, in send_secret_channel
    invite_link: ChatInviteLink = await bot.create_chat_invite_link(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2210, in create_chat_invite_link
    result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-25 00:19:35,177 - root - ERROR - ❌ 4-bosqich havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 80, in send_secret_channel
    invite_link: ChatInviteLink = await bot.create_chat_invite_link(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2210, in create_chat_invite_link
    result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-25 00:20:52,770 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-25 00:21:06,894 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-25 00:21:13,791 - root - ERROR - ❌ 1-bosqich havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 80, in send_secret_channel
    invite_link: ChatInviteLink = await bot.create_chat_invite_link(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2210, in create_chat_invite_link
    result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-25 00:21:14,085 - root - ERROR - ❌ 2-bosqich havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 80, in send_secret_channel
    invite_link: ChatInviteLink = await bot.create_chat_invite_link(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2210, in create_chat_invite_link
    result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-25 00:21:14,406 - root - ERROR - ❌ 3-bosqich havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 80, in send_secret_channel
    invite_link: ChatInviteLink = await bot.create_chat_invite_link(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2210, in create_chat_invite_link
    result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-25 00:21:14,717 - root - ERROR - ❌ 4-bosqich havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 80, in send_secret_channel
    invite_link: ChatInviteLink = await bot.create_chat_invite_link(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2210, in create_chat_invite_link
    result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-25 00:22:14,414 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2025-07-25 00:22:16,671 - root - ERROR - ❌ 1-bosqich havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 75, in send_secret_channel
    invite_link: ChatInviteLink = await bot.create_chat_invite_link(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2210, in create_chat_invite_link
    result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-25 00:22:16,978 - root - ERROR - ❌ 2-bosqich havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 75, in send_secret_channel
    invite_link: ChatInviteLink = await bot.create_chat_invite_link(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2210, in create_chat_invite_link
    result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-25 00:22:17,282 - root - ERROR - ❌ 3-bosqich havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 75, in send_secret_channel
    invite_link: ChatInviteLink = await bot.create_chat_invite_link(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2210, in create_chat_invite_link
    result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
2025-07-25 00:22:17,574 - root - ERROR - ❌ 4-bosqich havola yaratishda xatolik:
Traceback (most recent call last):
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/bot.py", line 75, in send_secret_channel
    invite_link: ChatInviteLink = await bot.create_chat_invite_link(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/bot.py", line 2210, in create_chat_invite_link
    result = await self.request(api.Methods.CREATE_CHAT_INVITE_LINK, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/bot/api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/kali/Desktop/N61 homeworks/bot projects/referal_bot/env/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.ChatNotFound: Chat not found
